# Generated by Django 3.2.7 on 2021-10-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
