# Generated by Django 3.2.7 on 2021-09-02 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='executors',
            field=models.ManyToManyField(related_name='proj_executors', to=settings.AUTH_USER_MODEL),
        ),
    ]
