# Generated by Django 2.2.23 on 2022-02-26 07:26

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kpkuser',
            managers=[
                ('objects', authapp.models.KpkUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='d_birth',
            field=models.DateField(null=True),
        ),
    ]
